apptrunk/urls.py
#
# Copyright (c) 2021, Grigoriy Kramarenko <root@rosix.ru>
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
from django.urls import path
from apptrunk.views import index, versions, upload, check, download

app_name = 'apptrunk'

urlpatterns = [
    path('', index, name='index'),
    path('upload', upload, name='upload'),
    path('upload/', upload, name='upload_with_slash'),
    path('versions/<str:project_name>/<path:branch_name>', versions, name='versions'),
    path('check/<str:project_name>/<path:branch_name>', check, name='check'),
    path('download/<str:project_name>/<path:branch_name>', download, name='download'),
]

server/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


def favicon(request):
    url = '%sapptrunk/img/favicon.png' % settings.STATIC_URL
    return redirect(url, permanent=False)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', favicon, name='favicon'),
    path('', include('apptrunk.urls', namespace='apptrunk')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apptrunk/forms.py
#
# Copyright (c) 2021, Grigoriy Kramarenko <root@rosix.ru>
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
from django import forms
from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils.dateparse import parse_datetime

from django.utils.timezone import utc, localtime
from django.utils.translation import gettext_lazy as _

from apptrunk.models import Project, Branch, Version
from apptrunk.utils import autoclean
from apptrunk.validators import validate_version, validate_suffix


class UploadForm(forms.ModelForm):
    """
    Форма для загрузки версии.
    """
    project = forms.CharField(max_length=50)
    branch = forms.CharField(max_length=50)
    version = forms.CharField(validators=[validate_version])
    semver = forms.CharField(required=False)
    timestamp = forms.CharField(required=False)

    class Meta:
        model = Version
        fields = (
            # 'major',
            # 'minor',
            # 'patch',
            # 'suffix',
            # 'semver',
            'package',
            'commit',
        )

    def clean_version(self):
        value = self.cleaned_data['version']
        groups = validate_version.regex.match(value).groups()
        major, minor, dot, patch, suffix = groups
        if minor is None:
            minor = 0
        if patch is None:
            patch = 0
        if suffix is None:
            suffix = ''

        # Исправление обрезки первичной точки в суффиксах `.dev*`.
        if suffix.startswith('dev'):
            suffix = f'.{suffix}'

        # Обработка передачи CI_COMMIT_TIMESTAMP в суффиксе.
        # Формат +2021-01-01T00:00:00+10:00 преобразовываем
        # в UTC и в число.
        if suffix.startswith('+'):
            datetime = parse_datetime(suffix[1:])
            if datetime:
                datetime = localtime(datetime, timezone=utc)
                suffix = '+%s' % datetime.strftime('%Y%m%d%H%M%S')
        # Формат -[alpha,beta,rc].2021-01-01T00:00:00+10:00 преобразовываем
        # в UTC и в число.
        elif '.' in suffix[1:]:
            head, tail = suffix.split('.', 1)
            datetime = parse_datetime(tail)
            if datetime:
                datetime = localtime(datetime, timezone=utc)
                suffix = '%s.%s' % (head, datetime.strftime('%Y%m%d%H%M%S'))

        if suffix:
            validate_suffix(suffix)

        return int(major), int(minor), int(patch or 0), suffix

    def clean_semver(self):
        return self.cleaned_data['semver'] not in ('false', 'no')

    def clean_timestamp(self):
        value = self.cleaned_data['timestamp'] or ''
        if value:
            datetime = parse_datetime(value)
            if datetime:
                datetime = localtime(datetime, timezone=utc)
                value = '+%s' % datetime.strftime('%Y%m%d%H%M%S')
            else:
                value = ''
        return value

    def clean(self):
        cdata = super().clean()
        project = cdata.get('project')
        branch = cdata.get('branch')
        version = cdata.get('version')
        if project and branch and version:
            ma, mi, pa, su = version
            # Суффикс, начинающийся на ".dev", обычно уже содержит время коммита.
            if su == '.dev' or not su.startswith('.dev'):
                su += cdata.get('timestamp', '')
            qs = Version.objects.filter(
                project__name=project,
                branch__name=branch,
                major=ma,
                minor=mi,
                patch=pa,
                suffix=su,
            )
            if qs.exists():
                v = '%s (%s): %d.%d.%d%s' % (
                    project,
                    branch,
                    ma,
                    mi,
                    pa,
                    su,
                )
                raise ValidationError(
                    _('Версия %r уже есть в хранилище.') % v
                )

    def save(self, **kwargs):
        instance = super().save(commit=False)
        cdata = self.cleaned_data

        ma, mi, pa, su = cdata['version']
        # Суффикс, начинающийся на ".dev", обычно уже содержит время коммита.
        if su == '.dev' or not su.startswith('.dev'):
            su += cdata.get('timestamp', '')
        instance.major = ma
        instance.minor = mi
        instance.patch = pa
        instance.suffix = su
        semver = cdata['semver']
        if semver and su and su[0] not in ('-', '+'):
            semver = False
        instance.semver = semver

        project, project_cr = Project.objects.get_or_create(
            name=cdata['project'],
        )
        branch, branch_cr = Branch.objects.get_or_create(
            project=project,
            name=cdata['branch'],
        )
        with transaction.atomic():
            instance.project = project
            instance.branch = branch
            instance.save()
            project.updated = instance.updated
            project.save(update_fields=['updated'])
            branch.updated = instance.updated
            branch.save(update_fields=['updated'])
            autoclean(instance)
        return instance

apptrunk/views.py
#
# Copyright (c) 2021, Grigoriy Kramarenko <root@rosix.ru>
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
import logging
from asgiref.sync import sync_to_async

from django.db.models import F, Q
from django.http import FileResponse, HttpResponse, Http404
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from apptrunk.forms import UploadForm
from apptrunk.models import Version
from apptrunk.decorators import client_access_required, system_access_required

logger = logging.getLogger(__name__)


def get_all_versions(client, project_name, branch_name):
    qs = Version.objects.filter(
        project__name=project_name,
        branch__name=branch_name,
    )
    if client:
        qs = qs.filter(project__restriction__client=client)
        qs = qs.filter(
            Q(project__restriction__branch__isnull=True) |
            Q(branch=F('project__restriction__branch')),
            Q(project__restriction__major_min__isnull=True) |
            Q(major__gte=F('project__restriction__major_min')),
            Q(project__restriction__minor_min__isnull=True) |
            Q(minor__gte=F('project__restriction__minor_min')),
            Q(project__restriction__major_max__isnull=True) |
            Q(major__lte=F('project__restriction__major_max')),
            Q(project__restriction__minor_max__isnull=True) |
            Q(minor__lte=F('project__restriction__minor_max')),
        )
    qs = qs.order_by('-major', '-minor', '-patch', '-is_release', '-created')
    return qs


def get_last_version(client, project_name, branch_name):
    qs = get_all_versions(client, project_name, branch_name)
    return qs.first()


@sync_to_async
@client_access_required
def index(request):

    if request.client:
        client_sql = """
    JOIN apptrunk_restriction ON (
        apptrunk_restriction.project_id = apptrunk_project.id
        AND (
            apptrunk_restriction.branch_id IS NULL
            OR
            apptrunk_restriction.branch_id = apptrunk_branch.id
        )
    )
    WHERE
        apptrunk_restriction.client_id = %s
        AND (
            apptrunk_restriction.major_min IS NULL
            OR
            apptrunk_version.major >= apptrunk_restriction.major_min
        )
        AND (
            apptrunk_restriction.minor_min IS NULL
            OR
            apptrunk_version.minor >= apptrunk_restriction.minor_min
        )
        AND (
            apptrunk_restriction.major_max IS NULL
            OR
            apptrunk_version.major <= apptrunk_restriction.major_max
        )
        AND (
            apptrunk_restriction.minor_max IS NULL
            OR
            apptrunk_version.minor <= apptrunk_restriction.minor_max
        )
        """
        params = [request.client.id]
    else:
        client_sql = ""
        params = []

    sql = f"""
SELECT *
FROM (
    SELECT
        apptrunk_version.*,
        apptrunk_project.name AS project_name,
        apptrunk_branch.name AS branch_name,
        RANK() OVER(
            PARTITION BY
                apptrunk_version.project_id,
                apptrunk_version.branch_id
            ORDER BY
                apptrunk_version.major DESC,
                apptrunk_version.minor DESC,
                apptrunk_version.patch DESC,
                apptrunk_version.is_release DESC,
                apptrunk_version.created DESC
        ) AS num
    FROM apptrunk_version
    JOIN apptrunk_project ON (apptrunk_project.id = apptrunk_version.project_id)
    JOIN apptrunk_branch ON (apptrunk_branch.id = apptrunk_version.branch_id)
    {client_sql}
) AS T0
WHERE
    num <= 10
ORDER BY
    project_name,
    branch_name,
    major DESC,
    minor DESC,
    patch DESC,
    is_release DESC,
    created DESC
    """

    qs = Version.objects.raw(sql, params)
    ctx = {'versions': qs}
    return render(request, 'apptrunk/index.html', ctx)


@sync_to_async
@client_access_required
def versions(request, project_name, branch_name):
    qs = get_all_versions(request.client, project_name, branch_name)
    ctx = {
        'versions': qs,
        'project_name': project_name,
        'branch_name': branch_name,
    }
    return render(request, 'apptrunk/versions.html', ctx)


@sync_to_async
@csrf_exempt
@system_access_required
@require_http_methods(['GET', 'POST'])
def upload(request):
    if request.method == 'GET':
        return HttpResponse('OK', content_type="text/plain")
    form = UploadForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return HttpResponse('OK', content_type="text/plain")
    lines = ['ERROR']
    for key, val in form.errors.items():
        if key != '__all__':
            lines.append('%s:' % key)
            tab = '\t'
        else:
            tab = ''
        for e in val:
            lines.append('%s%s' % (tab, e))
    lines.append('')
    return HttpResponse('\n'.join(lines), status=400, content_type="text/plain")


@sync_to_async
@client_access_required
def check(request, project_name, branch_name):
    version = get_last_version(request.client, project_name, branch_name)
    if not version:
        raise Http404
    return HttpResponse(version.get_version(), content_type="text/plain")


@sync_to_async
@client_access_required(or_system=True)
def download(request, project_name, branch_name):
    version = get_last_version(request.client, project_name, branch_name)
    if not version and 'or' in request.GET:
        branch_name = request.GET['or']
        version = get_last_version(request.client, project_name, branch_name)
    if not version:
        raise Http404
    filename, open_file = version.get_download_info()
    return FileResponse(open_file, as_attachment=True, filename=filename)

apptrunk/templates/apptrunk/_navbar.html
{% load i18n navigation %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top shadow pt-0 pb-0">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'apptrunk:index' %}">AppTrunk</a>
        <button class="navbar-toggler mr-1" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="{% trans 'Переключение навигации' %}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav px-3 w-100">

            </ul>
            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                {% if user.is_authenticated %}
                    <a href="{% url 'admin:logout' %}" class="nav-link">{% trans 'Выйти' %}</a>
                {% else %}
                    <a href="{% url 'admin:login' %}?next={{ request.get_full_path }}" class="nav-link">{% trans 'Войти' %}</a>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

apptrunk/templates/apptrunk/base.html
{% spaceless %}{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"ru" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <link href="{% static 'apptrunk/img/favicon.png' %}" rel="shortcut icon" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha256-djO3wMl9GeaC/u6K+ic4Uj/LKhRUSlUFcsruzS7v5ms=" crossorigin="anonymous">
    {% block style_page %}{% endblock %}
    <title>{% block title %}{% trans 'AppTrunk: выдача приложений клиентам.' %}{% endblock %}</title>
</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% include './_navbar.html' %}
<div class="container mt-5">
{% block container %}
    {% block content %}{% endblock %}
{% endblock %}
</div>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha256-fh8VA992XMpeCZiRuU4xii75UIG6KvHrbUF8yIS/2/4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/min/moment-with-locales.min.js" integrity="sha256-E3Snwx6F4t7DiA/L3DgPk6In2M1747JSau+3PWjtS5I=" crossorigin="anonymous"></script>
{% block javascript_page %}{% endblock %}
</body>
</html>
{% endspaceless %}

apptrunk/templates/apptrunk/index.html
{% extends 'apptrunk/base.html' %}{% load i18n %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'apptrunk:index' %}">AppTrunk</a></li>
        <li class="breadcrumb-item active" aria-current="page">{% trans 'Главная' %}</li>
    </ol>
</nav>

<h1 class="mb-2">{% trans 'Последние версии приложений.' %}</h1>

{% regroup versions by project_name as project_list %}

{% for project in project_list %}
<h2 class="mt-3">{{ project.grouper }}</h2>
<div class="row">
    {% regroup project.list by branch_name as branch_list %}
    {% for branch in branch_list %}
    <div class="col-md-6 col-lg-4">
        <h3>
            <a href="{% url 'apptrunk:versions' project_name=project.grouper branch_name=branch.grouper %}">
                {{ branch.grouper }}
            </a>
        </h3>
        <table class="table">
            <tbody>
                {% for version in branch.list %}
                <tr>
                    <td>
                        <code>{{ version }}</code>
                        <br>
                        <span class="text-muted"> {{ version.updated }}</span>
                    </td>
                    <td>
                        {% if version.is_release %}
                        <span class="badge bg-success">relese</span>
                        {% else %}
                        <span class="badge bg-warning">pre-relese</span>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
</div>
{% endfor %}

{% endblock %}

apptrunk/templates/apptrunk/versions.html
{% extends 'apptrunk/base.html' %}{% load i18n %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'apptrunk:index' %}">AppTrunk</a></li>
        <li class="breadcrumb-item active" aria-current="page">{% trans 'Версии ветки проекта' %}</li>
    </ol>
</nav>

<h1 class="mb-2">{% blocktrans %}{{ project_name }}: ветка <code>{{ branch_name }}</code>.{% endblocktrans %}</h1>

<table class="table">
    <tbody>
        {% for version in versions %}
        <tr>
            <td>
                <code>{{ version }}</code>
                <br>
                <span class="text-muted"> {{ version.updated }}</span>
            </td>
            <td>
                {% if version.is_release %}
                <span class="badge bg-success">relese</span>
                {% else %}
                <span class="badge bg-warning">pre-relese</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}